### ISSUE TITLE
Install problem n Ubuntu server

### ISSUE THREAD

**Issue by Kurosama** [sourcemint/sm#12]
I've install sm in Ubuntu server.

```
kurosama@ServerTest:~$ sudo npm install -g sm

npm http GET https://registry.npmjs.org/sm
npm http 304 https://registry.npmjs.org/sm

> sm@0.3.6-pre.60 postinstall /usr/local/lib/node_modules/sm
> node ./scripts/postinstall.js

Installing default sm toolchain at: /home/kurosama/.sm
  * ERROR ***************************************************************************
  * Error: Object #<Object> has no method 'exists' (type)
  * File : /usr/local/lib/node_modules/sm/lib/scanner.js @ 133 : 9
  * Stack:
  *        at /usr/local/lib/node_modules/sm/lib/scanner.js:164:5
  *        at Array.0 (/usr/local/lib/node_modules/sm/node_modules/sm-util/node_modules/waitfor/lib/waitfor.js:114:28)
  *    From previous event:
  *        at [object Object].status (/usr/local/lib/node_modules/sm/lib/sm-core.js:256:31)
  *        at Command.<anonymous> (/usr/local/lib/node_modules/sm/lib/sm-cli.js:109:16)
  *        at Command.<anonymous> (/usr/local/lib/node_modules/sm/node_modules/commander/lib/commander.js:235:8)
  *        at Command.emit (events.js:88:20)
  *        at Command.parseArgs (/usr/local/lib/node_modules/sm/node_modules/commander/lib/commander.js:406:12)
  *        at Command.parse (/usr/local/lib/node_modules/sm/node_modules/commander/lib/commander.js:352:15)
  *        at /usr/local/lib/node_modules/sm/lib/sm-cli.js:344:13
  * ERROR ***************************************************************************
npm ERR! error installing sm@0.3.6-pre.60

npm ERR! sm@0.3.6-pre.60 postinstall: `node ./scripts/postinstall.js`
npm ERR! `sh "-c" "node ./scripts/postinstall.js"` failed with 1
npm ERR! 
npm ERR! Failed at the sm@0.3.6-pre.60 postinstall script.
npm ERR! This is most likely a problem with the sm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sm
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.2.0-38-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "sm"
npm ERR! cwd /home/kurosama
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message sm@0.3.6-pre.60 postinstall: `node ./scripts/postinstall.js`
npm ERR! message `sh "-c" "node ./scripts/postinstall.js"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/kurosama/npm-debug.log
npm not ok
```

And I've install

```
npm -v
1.1.4

node -v
v0.8.20

Linux ServerUbuntu 3.2.0-38-generic-pae #61-Ubuntu SMP Tue Feb 19 12:39:51 UTC 2013 i686 athlon i386 GNU/Linux
```

**Comment by cadorn** [comment]
This repo holds `sm@0.3` which is not quite ready for use yet.

You can use `sm@0.2` today. See: https://github.com/sourcemint/sm-npm

**Comment by bejoyfuuul** [comment]
["0.0.1","0.1.2","0.1.3","0.1.4","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10",
"0.1.11","0.1.12","0.1.13","0.1.14","0.1.15","0.1.16","0.1.17","0.1.23",
"0.1.24","0.1.25","0.1.26","0.1.27","0.1.29","0.1.30","0.1.31","0.1.33",
"0.1.38","0.1.39","0.1.40","0.1.41","0.1.45","0.1.46","0.1.47","0.1.48",
"0.1.49","0.1.50","0.1.51","0.1.52","0.1.53","0.1.54","0.1.55","0.1.57",
"0.1.58","0.1.59","0.1.60","0.1.61","0.1.62","0.1.63","0.1.64","0.1.65",
"0.1.66","0.1.67","0.1.68","0.1.69",
"0.3.6-pre.17","0.3.6-pre.18","0.3.6-pre.19","0.3.6-pre.20","0.3.6-pre.21",
"0.3.6-pre.22","0.3.6-pre.23","0.3.6-pre.36","0.3.6-pre.40","0.3.6-pre.41",
"0.3.6-pre.42","0.3.6-pre.43","0.3.6-pre.44","0.3.6-pre.46","0.3.6-pre.47",
"0.3.6-pre.48","0.3.6-pre.54","0.3.6-pre.56","0.3.6-pre.57","0.3.6-pre.58",
"0.3.6-pre.59","0.3.6-pre.60","0.3.6-pre.63"]

choose version

sudo npm install -g sm@{version}

ex) sudo npm install -g sm@0.1.69

:smile:
