### ISSUE TITLE
Cannot find sm@0.2

### ISSUE THREAD

**Issue by pfweller** [sourcemint/sm#13]
I hit the same issue as #12, but I cannot install 0.2 as `npm` is unable to find it. Oddly, the versiom mentioned [on npmjs.org](https://npmjs.org/package/sm) is 0.2.11.

```
$ npm install sm@0.2
npm http GET https://registry.npmjs.org/sm
npm http 304 https://registry.npmjs.org/sm

npm ERR! Error: No compatible version found: sm@'>=0.2.0- <0.3.0-'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.3.6-pre.17","0.3.6-pre.18","0.3.6-pre.19","0.3.6-pre.20","0.3.6-pre.21","0.3.6-pre.22","0.3.6-pre.23","0.3.6-pre.36","0.3.6-pre.40","0.3.6-pre.41","0.3.6-pre.42","0.3.6-pre.43","0.3.6-pre.44","0.3.6-pre.46","0.3.6-pre.47","0.3.6-pre.48","0.3.6-pre.54","0.3.6-pre.56","0.3.6-pre.57","0.3.6-pre.58","0.3.6-pre.59","0.3.6-pre.60","0.3.6-pre.63"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pfweller/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-39-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install" "sm@0.2"
npm ERR! cwd /home/pfweller
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: sm@'>=0.2.0- <0.3.0-'
npm ERR! message Valid install targets:
npm ERR! message ["0.0.1","0.3.6-pre.17","0.3.6-pre.18","0.3.6-pre.19","0.3.6-pre.20","0.3.6-pre.21","0.3.6-pre.22","0.3.6-pre.23","0.3.6-pre.36","0.3.6-pre.40","0.3.6-pre.41","0.3.6-pre.42","0.3.6-pre.43","0.3.6-pre.44","0.3.6-pre.46","0.3.6-pre.47","0.3.6-pre.48","0.3.6-pre.54","0.3.6-pre.56","0.3.6-pre.57","0.3.6-pre.58","0.3.6-pre.59","0.3.6-pre.60","0.3.6-pre.63"]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pfweller/npm-debug.log
npm not ok
```

**Comment by cadorn** [comment]
What version of node are you on?

Try `npm install sm@0.2.11`

**Comment by pfweller** [comment]
Looks like that was the issue. My node & npm versions are a bit old, but that's an issue on my end.

Before I close this issue, do you have any idea why npmjs.org wasn't reporting `0.2.11` as one of the valid install targets?

**Comment by cadorn** [comment]
The only reason I can think of is that you were using node < 0.6.15 which is the min node version declared in package.json for `sm`.

**Comment by pfweller** [comment]
That would make sense. Thank you!
