### ISSUE TITLE
sm: Cannot find module 'sourcemint-util-js/lib/os'

### ISSUE THREAD

**Issue by drook** [sourcemint/sm#5]
After installing with npm sm is missing a module. This issue comes up right during the installation:

```
npm http 304 https://registry.npmjs.org/graceful-fs
/usr/local/node.js/bin/sm -> /usr/local/node.js/lib/node_modules/sm/bin/sm

> sm@0.2.11 postinstall /usr/local/node.js/lib/node_modules/sm
> node ./scripts/postinstall.js

Uncaught exception: Error: Cannot find module 'sourcemint-util-js/lib/os'
sm@0.2.11 /usr/local/node.js/lib/node_modules/sm
├── semver@1.1.1
├── sourcemint-pinf-js@0.1.7
├── sourcemint-util-js@0.1.53 (wrench@1.3.9, n-util@0.0.1, q@0.8.5, console-trace@0.1.0, glob@3.1.12)
└── sourcemint-pm-sm@0.1.33 (sourcemint-pm-zip@0.1.1, sourcemint-pm-url@0.1.2, mappings@0.1.5, sourcemint-pm-git@0.1.22, sourcemint-pm-npm@0.1.19, sourcemint-deployer@0.1.5, prompt@0.2.3, sourcemint-pm-tar@0.1.6)
```

And then of course each time I launch the sm:

```
> sm
Uncaught exception: Error: Cannot find module 'sourcemint-util-js/lib/os'

> node -v
v0.8.16

> uname -a
SunOS hyperion 5.11 11.1 i86pc i386 i86pc
```

And there is no lib/os directory in the module tree.

**Comment by drook** [comment]
I ran it interactively and here's what I got:

```
> require("../lib/cli").main();
Error: Cannot find module 'sourcemint-util-js/lib/os'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/node.js/lib/node_modules/sm/lib/commands/install-command.js:7:12)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```

**Comment by drook** [comment]
It's an install-command.js file, line 7:

```
const OS = require("sourcemint-util-js/lib/os");
```

**Comment by cadorn** [comment]
Looks like you are running `https://github.com/sourcemint/sm-npm/` from `master`. This will get you a dev version which is currently a work in progress.

If you want to run from source, clone `https://github.com/sourcemint/sm-npm/` and checkout tag `v0.2.11`.
